MTKPM-QuanLyKhachSan/Controllers/PublicRoomController.cs
using Microsoft.AspNetCore.Mvc;
using MTKPM_QuanLyKhachSan.Daos;
using MTKPM_QuanLyKhachSan.Models;
using MTKPM_QuanLyKhachSan.ViewModels;

namespace MTKPM_QuanLyKhachSan.Controllers
{
    public class PublicRoomController : Controller
    {
        RoomTypeDao roomTypeDao;
        RoomDao roomDao;
        BookRoomDao bookRoomDao;
        BookRoomDetailsDao bookRoomDetailsDao;

        public PublicRoomController(DatabaseContext context)
        {
            roomTypeDao = new RoomTypeDao(context);
            roomDao = new RoomDao(context);
            bookRoomDao = new BookRoomDao(context);
            bookRoomDetailsDao = new BookRoomDetailsDao(context);
        }

        public IActionResult Index(SearchRoomTypeVM searchRoomTypeVM)
        {
            ViewBag.PageTitle = "Phòng";

            if (searchRoomTypeVM.NumAdult > 0 && searchRoomTypeVM.NumChildren > 0)
            {
                ViewBag.rooms = roomTypeDao.SearchRoomType
                (
                    searchRoomTypeVM.CheckIn,
                    searchRoomTypeVM.CheckOut,
                    searchRoomTypeVM.NumAdult,
                    searchRoomTypeVM.NumChildren
                );
            }
            else
            {
                ViewBag.rooms = roomTypeDao.GetRoomTypes(HttpContext.Session.GetInt32("HotelId"));
            }

            return View();
        }

        public IActionResult RoomDetails(int roomTypeId)
        {
            ViewBag.PageTitle = "Chi tiết phòng";
            ViewBag.roomTypeDetails = roomTypeDao.GetRoomTypeById(roomTypeId);
            return View();
        }

        public IActionResult Booking()
        {
            ViewBag.roomTypes = roomTypeDao.GetRoomTypes(HttpContext.Session.GetInt32("HotelId"));

			if (HttpContext.Session.GetInt32("CustomerId") == null)
			{
				return RedirectToAction("Login", "PublicCustomer");
			}
			else
			{
				return View();
			}
        }

        [HttpPost]
        public IActionResult Booking(BookingVM bookingVM)
        {
            ViewBag.roomTypes = roomTypeDao.GetRoomTypes(HttpContext.Session.GetInt32("HotelId"));

            ViewModels.ExecutionOutcome executeOperation;

            if (roomDao.RoomStatus(bookingVM.RoomId) != 0)
            {
                executeOperation = new ViewModels.ExecutionOutcome()
                {
                    Result = false,
                    Mess = "Phòng đã có người đặt. Vui lòng chọn phòng khác.",
                };
            } 
            else if (int.Parse(bookingVM.Phone) <= 0 || bookingVM.Phone.Length > 10)
            {
                executeOperation = new ViewModels.ExecutionOutcome()
                {
                    Result = false,
                    Mess = "Vui lòng nhập đúng định dạng số điện thoại.",
                };
            }
            else if (bookingVM.CheckDate() == false)
            {
                executeOperation = new ViewModels.ExecutionOutcome()
                {
                    Result = false,
                    Mess = "Ngày đi phải nhỏ hơn ngày tới.",
                };
            }
            else
            {
                BookRoom bookRoom = new BookRoom()
                {
                    CustomerId = (int)HttpContext.Session.GetInt32("CustomerId"),
                    Note = bookingVM.Note,
                    NumAdult = bookingVM.NumAdult,
                    NumChildren = bookingVM.NumChildren,
                };

                bookRoomDao.Booking(bookRoom);

                BookRoomDetails bookRoomDetails = new BookRoomDetails()
                {
                    BookRoomId = bookRoom.BookRoomId,
                    RoomId = bookingVM.RoomId,
                    CheckIn = bookingVM.ConvertDateTime(bookingVM.CheckIn),
                    CheckOut = bookingVM.ConvertDateTime(bookingVM.CheckOut),
                };

                bookRoomDetailsDao.AddBookRoomDetails(bookRoomDetails);

                executeOperation = new ViewModels.ExecutionOutcome()
                {
                    Result = true,
                    Mess = "Đã đặt phòng thành công.",
                };
            }

            return Json(executeOperation);
        }

        [HttpPost]
        public IActionResult RoomPartialView(int roomTypeId)
        {
            ViewBag.rooms = roomDao.GetEmptyRoomByType(roomTypeId);
            return PartialView();
        }
    } 
}

MTKPM-QuanLyKhachSan/Views/PublicRoom/Booking.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Views/Shared/_CustomerLayout.cshtml";
	var roomTypes = ViewBag.roomTypes;
}
@model BookingVM

<!-- Booking Start -->
<div class="container-xxl py-5">
	<div class="container">
		<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
			<h6 class="section-title text-center text-primary text-uppercase">Room Booking</h6>
			<h1 class="mb-5">Book A <span class="text-primary text-uppercase">Luxury Room</span></h1>
		</div>
		<div class="row g-5">
			<div class="col-lg-6">
				<div class="row g-3">
					<div class="col-6 text-end">
						<img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.1s" src="~/customer/img/about-1.jpg" style="margin-top: 25%;">
					</div>
					<div class="col-6 text-start">
						<img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.3s" src="~/customer/img/about-2.jpg">
					</div>
					<div class="col-6 text-end">
						<img class="img-fluid rounded w-50 wow zoomIn" data-wow-delay="0.5s" src="~/customer/img/about-3.jpg">
					</div>
					<div class="col-6 text-start">
						<img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.7s" src="~/customer/img/about-4.jpg">
					</div>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="wow fadeInUp" data-wow-delay="0.2s">
					<form id="form-booking">
						<div class="row g-3">
							<div class="col-md-6">
								<div class="form-floating">
									<input asp-for="Name" type="text" class="form-control" id="name" placeholder="Your Name" required>
									<label for="name">Tên của bạn</label>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-floating">
									<input asp-for="Phone" type="number" class="form-control" id="phone" placeholder="Your Phone" required>
									<label for="phone">Số điện thoại</label>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-floating date" id="date3" data-target-input="nearest">
									<input asp-for="CheckIn" type="text" readonly class="form-control date-input" id="checkin" placeholder="Check In" required/>
									<label for="checkin">Ngày nhận</label>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-floating date" id="date4" data-target-input="nearest">
									<input asp-for="CheckOut" type="text" readonly class="form-control date-input" id="checkout" placeholder="Check Out" required/>
									<label for="checkout">Ngày trả</label>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-floating">
									<select class="form-select" id="numAdult">
										<option value="1">1 người lớn</option>
										<option value="2">2 người lớn</option>
										<option value="3">3 người lớn</option>
										<option value="4">4 người lớn</option>
									</select>
									<label for="select1">Số người lớn</label>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-floating">
									<select class="form-select" id="numChildren">
										<option value="1">1 trẻ em</option>
										<option value="2">2 trẻ em</option>
										<option value="3">3 trẻ em</option>
										<option value="4">4 trẻ em</option>
									</select>
									<label for="select2">Số trẻ em</label>
								</div>
							</div>

							<div class="col-6">
								<div class="form-floating">
									<select class="form-select" id="select-room-type">
										@foreach (var item in roomTypes)
										{
											<option value="@item.RoomTypeId">@item.Name</option>
										}
									</select>
									<label for="select3">Loại phòng</label>
								</div>
							</div>

							<div class="col-6" id="render-room-partial-view">
							</div>

							<div class="col-12">
								<div class="form-floating">
									<textarea asp-for="Note" class="form-control" placeholder="Special Request" id="note" style="height: 100px"></textarea>
									<label for="message">Special Request</label>
								</div>
							</div>

							<div class="col-12">
								<a id="btn-submit" class="btn btn-primary w-100 py-3">Đặt ngay</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Booking End -->

<script type="module" src="~/customer/js/public-booking.js"></script>

MTKPM-QuanLyKhachSan/Views/PublicRoom/Index.cshtml
@{
	Layout = "~/Views/Shared/_CustomerLayout.cshtml";
	var rooms = ViewBag.rooms;
}

<!-- Room Start -->
<div class="container-xxl py-5">
	<div class="container">
		<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
			<h6 class="section-title text-center text-primary text-uppercase">Our Rooms</h6>
			<h1 class="mb-5">Explore Our <span class="text-primary text-uppercase">Rooms</span></h1>
		</div>
		<div class="row g-4">
			@foreach (var  item in rooms)
			{
				<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
					<div class="room-item shadow rounded overflow-hidden">
						<div class="position-relative">
							<img class="img-fluid" src="~/customer/img/room-1.jpg" alt="">
							<small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">@item.FormatCurrency()/đêm</small>
						</div>
						<div class="p-4 mt-2">
							<div class="d-flex justify-content-between mb-3">
								<h5 class="mb-0">@item.Name</h5>
								<div class="ps-2">
									<small class="fa fa-star text-primary"></small>
									<small class="fa fa-star text-primary"></small>
									<small class="fa fa-star text-primary"></small>
									<small class="fa fa-star text-primary"></small>
									<small class="fa fa-star text-primary"></small>
								</div>
							</div>
							<div class="d-flex mb-3 justify-content-between">
								<small class="border-end me-2 pe-3"><i class="fa fa-bed text-primary me-2"></i>3 Giường</small>
								<small class="border-end me-2 pe-3"><i class="fa fa-bath text-primary me-2"></i>2 bồn tắm</small>
								<small class="border-end me-2 pe-3"><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
								<small><i class="fa-solid fa-door-open text-primary me-2"></i>10/20</small>
							</div>
							<p class="text-body mb-3 limit-2-lines">@item.ShortDesc()</p>
							<div class="d-flex justify-content-between">
								<a asp-controller="PublicRoom" asp-action="RoomDetails" asp-route-roomTypeId="@item.RoomTypeId" class="btn btn-sm btn-primary rounded py-2 px-4">Xem chi tiết</a>
								<a class="btn btn-sm btn-dark rounded py-2 px-4" href="">Đặt ngay</a>
							</div>
						</div>
					</div>
				</div>
			}
			@*<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
				<div class="room-item shadow rounded overflow-hidden">
					<div class="position-relative">
						<img class="img-fluid" src="~/customer/img/room-2.jpg" alt="">
						<small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">$100/Night</small>
					</div>
					<div class="p-4 mt-2">
						<div class="d-flex justify-content-between mb-3">
							<h5 class="mb-0">Executive Suite</h5>
							<div class="ps-2">
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
							</div>
						</div>
						<div class="d-flex mb-3">
							<small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>
							<small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>
							<small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
						</div>
						<p class="text-body mb-3">Erat ipsum justo amet duo et elitr dolor, est duo duo eos lorem sed diam stet diam sed stet lorem.</p>
						<div class="d-flex justify-content-between">
							<a class="btn btn-sm btn-primary rounded py-2 px-4" href="">View Detail</a>
							<a class="btn btn-sm btn-dark rounded py-2 px-4" href="">Book Now</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
				<div class="room-item shadow rounded overflow-hidden">
					<div class="position-relative">
						<img class="img-fluid" src="~/customer/img/room-3.jpg" alt="">
						<small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">$100/Night</small>
					</div>
					<div class="p-4 mt-2">
						<div class="d-flex justify-content-between mb-3">
							<h5 class="mb-0">Super Deluxe</h5>
							<div class="ps-2">
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
							</div>
						</div>
						<div class="d-flex mb-3">
							<small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>
							<small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>
							<small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
						</div>
						<p class="text-body mb-3">Erat ipsum justo amet duo et elitr dolor, est duo duo eos lorem sed diam stet diam sed stet lorem.</p>
						<div class="d-flex justify-content-between">
							<a class="btn btn-sm btn-primary rounded py-2 px-4" href="">View Detail</a>
							<a class="btn btn-sm btn-dark rounded py-2 px-4" href="">Book Now</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
				<div class="room-item shadow rounded overflow-hidden">
					<div class="position-relative">
						<img class="img-fluid" src="~/customer/img/room-3.jpg" alt="">
						<small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">$100/Night</small>
					</div>
					<div class="p-4 mt-2">
						<div class="d-flex justify-content-between mb-3">
							<h5 class="mb-0">Super Deluxe</h5>
							<div class="ps-2">
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
							</div>
						</div>
						<div class="d-flex mb-3">
							<small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>
							<small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>
							<small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
						</div>
						<p class="text-body mb-3">Erat ipsum justo amet duo et elitr dolor, est duo duo eos lorem sed diam stet diam sed stet lorem.</p>
						<div class="d-flex justify-content-between">
							<a class="btn btn-sm btn-primary rounded py-2 px-4" href="">View Detail</a>
							<a class="btn btn-sm btn-dark rounded py-2 px-4" href="">Book Now</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
				<div class="room-item shadow rounded overflow-hidden">
					<div class="position-relative">
						<img class="img-fluid" src="~/customer/img/room-1.jpg" alt="">
						<small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">$100/Night</small>
					</div>
					<div class="p-4 mt-2">
						<div class="d-flex justify-content-between mb-3">
							<h5 class="mb-0">Junior Suite</h5>
							<div class="ps-2">
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
							</div>
						</div>
						<div class="d-flex mb-3">
							<small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>
							<small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>
							<small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
						</div>
						<p class="text-body mb-3">Erat ipsum justo amet duo et elitr dolor, est duo duo eos lorem sed diam stet diam sed stet lorem.</p>
						<div class="d-flex justify-content-between">
							<a class="btn btn-sm btn-primary rounded py-2 px-4" href="">View Detail</a>
							<a class="btn btn-sm btn-dark rounded py-2 px-4" href="">Book Now</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
				<div class="room-item shadow rounded overflow-hidden">
					<div class="position-relative">
						<img class="img-fluid" src="~/customer/img/room-2.jpg" alt="">
						<small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">$100/Night</small>
					</div>
					<div class="p-4 mt-2">
						<div class="d-flex justify-content-between mb-3">
							<h5 class="mb-0">Executive Suite</h5>
							<div class="ps-2">
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
								<small class="fa fa-star text-primary"></small>
							</div>
						</div>
						<div class="d-flex mb-3">
							<small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>
							<small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>
							<small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
						</div>
						<p class="text-body mb-3">Erat ipsum justo amet duo et elitr dolor, est duo duo eos lorem sed diam stet diam sed stet lorem.</p>
						<div class="d-flex justify-content-between">
							<a class="btn btn-sm btn-primary rounded py-2 px-4" href="">View Detail</a>
							<a class="btn btn-sm btn-dark rounded py-2 px-4" href="">Book Now</a>
						</div>
					</div>
				</div>
			</div>*@
		</div>
	</div>
</div>
<!-- Room End -->


<!-- Testimonial Start -->
@Html.Partial("_TestimonialPartial");
<!-- Testimonial Start -->

MTKPM-QuanLyKhachSan/Views/PublicRoom/RoomDetails.cshtml
@{
	Layout = "~/Views/Shared/_CustomerLayout.cshtml";
	var roomTypeDetails = ViewBag.roomTypeDetails;
}

<!-- Room Details Section Begin -->
<section class="room-details-section spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="room-details-item">
					<img src="~/img/room-details.jpg" style="width: 100%" alt="">
					<div class="rd-text">
						<div class="rd-title">
							<h3>@roomTypeDetails.Name</h3>
							<div class="rdt-right">
								<div class="rating">
									<i class="fa-solid fa-star"></i>
									<i class="fa-solid fa-star"></i>
									<i class="fa-solid fa-star"></i>
									<i class="fa-solid fa-star"></i>
									<i class="fa-solid fa-star-half"></i>
								</div>
								<a href="#">Đặt ngay</a>
							</div>
						</div>
						<h2>@roomTypeDetails.FormatCurrency()<span>/đêm</span></h2>
						<table>
							<tbody>
								<tr>
									<td class="r-o">Kích thước:</td>
									<td>30 ft</td>
								</tr>
								<tr>
									<td class="r-o">Số người tối đa:</td>
									<td>@(roomTypeDetails.NumChildren + roomTypeDetails.NumAdult)</td>
								</tr>
								<tr>
									<td class="r-o">Giường:</td>
									<td>@roomTypeDetails.NumBed</td>
								</tr>
								<tr>
									<td class="r-o">Dịch vụ:</td>
									<td>Wifi, TiVi, Phòng tắm,...</td>
								</tr>
							</tbody>
						</table>
						@Html.Raw(@roomTypeDetails.Description)
					</div>
				</div>
				<div class="rd-reviews">
					<h4>Đánh giá</h4>
					<div class="review-item">
						<div class="ri-pic">
							<img src="~/img/avatar-1.jpg" alt="">
						</div>
						<div class="ri-text">
							<span>27 Aug 2019</span>
							<div class="rating">
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star-half"></i>
							</div>
							<h5>Brandon Kelley</h5>
							<p>
								Neque porro qui squam est, qui dolorem ipsum quia dolor sit amet, consectetur,
								adipisci velit, sed quia non numquam eius modi tempora. incidunt ut labore et dolore
								magnam.
							</p>
						</div>
					</div>
				</div>
				<div class="review-add">
					<h4>Thêm đánh giá</h4>
					<form action="#" class="ra-form">
						<div class="row">
							<div class="col-lg-6">
								<input type="text" placeholder="Tên của bạn*">
							</div>
							<div class="col-lg-6">
								<input type="text" placeholder="Email*">
							</div>
							<div class="col-lg-12">
								<div>
									<h5>Đánh giá của bạn:</h5>
									<div class="rating">
										<i class="fa-solid fa-star"></i>
										<i class="fa-solid fa-star"></i>
										<i class="fa-solid fa-star"></i>
										<i class="fa-solid fa-star"></i>
										<i class="fa-solid fa-star"></i>
									</div>
								</div>
								<textarea placeholder="Your Review"></textarea>
								<button type="submit">Gửi</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="room-booking">
					<h3>Đặt phòng</h3>
					<form action="#">
						<div class="check-date">
							<label for="date-in">Check In:</label>
							<input type="text" class="date-input" id="date-in" placeholder=". . / . . / . ." readonly>
							<i class="fa-regular fa-calendar"></i>
						</div>

						<div class="check-date">
							<label for="date-out">Check Out:</label>
							<input type="text" class="date-input" id="date-out" placeholder=". . / . . / . ." readonly>
							<i class="fa-regular fa-calendar"></i>
						</div>

						<div class="select-option">
							<label for="guest">Guests:</label>
							<select id="guest" class="nice-select">
								<option value="1">1 Adults</option>
								<option value="2">2 Adults</option>
								<option value="3">3 Adults</option>
								<option value="4">4 Adults</option>
							</select>
						</div>

						<div class="select-option">
							<label for="room">Room:</label>
							<select id="room" class="nice-select">
								<option value="1">1 Room</option>
								<option value="2">2 Room</option>
								<option value="3">3 Room</option>
								<option value="4">4 Room</option>
							</select>
						</div>

						<button type="submit">Kiểm tra tình trạng</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Room Details Section End -->

@*<script>
	$(function(){
		$('.date-input').datepicker({
			minDate: 0,
			dateFormat: 'dd MM, yy'
		});
	})
</script>*@

MTKPM-QuanLyKhachSan/Views/PublicRoom/RoomPartialView.cshtml
@{
	var rooms = ViewBag.rooms;
}

<div class="form-floating">
	<select class="form-select" id="roomId">
		@foreach (var item in rooms)
		{
			<option value="@item.RoomId">@item.Name</option>
		}
	</select>
	<label for="select3">Phòng</label>
</div>