MTKPM-QuanLyKhachSan/Areas/Admin/Controllers/AdminRoomTypeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using MTKPM_QuanLyKhachSan.Daos;
using MTKPM_QuanLyKhachSan.Models;
using MTKPM_QuanLyKhachSan.ViewModels;
using System.Diagnostics;
using System.Drawing.Drawing2D;
using System;
using MTKPM_QuanLyKhachSan.Areas.Admin.DesignPattern.Strategy;
using Humanizer.Localisation.TimeToClockNotation;
using MTKPM_QuanLyKhachSan.Common.Config;

namespace MTKPM_QuanLyKhachSan.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("Admin/[controller]/[action]")]
	public class AdminRoomTypeController : Controller
	{
		RoomTypeDao roomTypeDao;
		private readonly IWebHostEnvironment _hostEnvironment;
		IService myService;

		public AdminRoomTypeController(DatabaseContext context, IService myService)
		{
			this.myService = myService;
			roomTypeDao = new RoomTypeDao(context);
		}
		public IActionResult Index()
		{
			ViewBag.RoomType = roomTypeDao.GetRoomTypes1();
			return View();
		}
		[HttpGet]
		public IActionResult AddRoomType()
		{
			return View();
		}
		[HttpPost]
		public IActionResult AddRoomType(RoomTypeVM roomTypeVM)
		{
			IFormFile imageFile = roomTypeVM.ImageFile;
			ModelState.Remove("Image");
			ModelState.Remove("ImageFile");
			ModelState.Remove("RoomTypeId");
			ModelState.Remove("NumView");
			if (ModelState.IsValid)
			{
				if (imageFile != null && imageFile.Length > 0)
				{
					// Đảm bảo đường dẫn thư mục image
					var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "Content/HinhAnhSP");

					// Tạo tên tệp ảnh duy nhất bằng cách sử dụng Guid và đuôi tệp ảnh ban đầu
					var fileName = Guid.NewGuid().ToString() + Path.GetExtension(imageFile.FileName);

					// Kết hợp đường dẫn đến thư mục image và tên tệp ảnh để có đường dẫn đầy đủ
					var filePath = Path.Combine(imagePath, fileName);

					// Lưu tệp ảnh vào thư mục image
					using (var stream = new FileStream(filePath, FileMode.Create))
					{
						imageFile.CopyTo(stream);
					}

					// Lưu đường dẫn tệp ảnh vào thuộc tính Image của sản phẩm
					roomTypeVM.Image = fileName;
				}
				RoomType roomType = new RoomType()
				{
					RoomTypeId = roomTypeVM.RoomTypeId,
					Name = roomTypeVM.Name,
					Price = roomTypeVM.Price,
					Description = roomTypeVM.Description,
					NumBed = roomTypeVM.NumBed,
					NumAdult = roomTypeVM.NumAdult,
					NumChildren = roomTypeVM.NumChildren,
					NumView = roomTypeVM.NumView,
					HotelId = myService.GetHotelId()
				};

				roomTypeDao.InsertRoomType(roomType);
				return RedirectToAction("Index");
			}
			return View();
		}
	}
}

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoomType/AddRoomType.cshtml
@addTagHelper *, Microsoft.AspNetCore.MVC.TagHelpers
@using MTKPM_QuanLyKhachSan.ViewModels
@model RoomTypeVM

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="colorlib.com">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="~/admin/assets/adminRoomtype/fonts/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/admin/assets/adminRoomtype/vendor/nouislider/nouislider.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="~/admin/assets/adminRoomtype/css/style.css">
</head>

<body>

    <div class="main">

        <div class="container">
            <form method="POST" id="signup-form" class="signup-form" asp-controller="AdminRoomType" asp-action="AddRoomType" asp-area="Admin">
                <div>
                    <h3>Loại Phòng </h3>
                    <fieldset>
                        <h2>Thêm Loại Phòng</h2> 
                        <div class="fieldset-content">
                            <div class="form-row">   
                                <div class="form-flex">
                                    <div class="form-group">
                                        <label class="form-label">Tên</label>
                                        <input type="text"  id="first_name" asp-for="Name"/>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Giá</label>
                                        <input type="text"  id="last_name" asp-for="Price"  />
                                    </div>
                                </div>
                            </div>     
                            <div class="form-row">
                                @*<label for="birth_date" class="form-label">Số Giường</label>*@
                                <div class="form-flex">
                                    <div class="form-group">
                                        <label class="form-label">Tổng số giường</label>
                                        <input type="text" id="first_name" asp-for="NumBed" />
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Giường người lớn</label>
                                        <input type="text"  id="last_name" asp-for="NumAdult" type="number" />
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Giường em bé</label>
                                        <input type="text"  id="last_name" asp-for="NumChildren" type="number" />
                                    </div>           
                                </div>
                            </div>
                            <div class="form-group">
                                @*<label  for="ssn" class="form-label">Hình ảnh</label>
                                <input width: 300px type="text" name="ssn" id="ssn" />*@
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="ssn" class="form-label">Mô tả</label>
                                    <textarea class="form-control" id="message" cols="30" rows="7" asp-for="Description" type="text"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="">
                        <input id="submit-input" type="submit"  value="Lưu">
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>

    <!-- JS -->
    <script src="~/admin/assets/adminRoomtype/vendor/jquery/jquery.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/jquery-steps/jquery.steps.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/minimalist-picker/dobpicker.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/nouislider/nouislider.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/wnumb/wNumb.js"></script>
    <script src="~/admin/assets/adminRoomtype/js/main.js"></script>*
</body>

</html>

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoomType/Index.cshtml
﻿﻿@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	var RoomType = ViewBag.RoomType;
}
@model RoomTypeVM
<div class="main-container d-flex">
	<!-- Nội dung bên trái -->
	<div class="left-panel col-8 pl-0 pr-0">
		<div class="content container-fluid">
			<div class="page-header">
				<div class="row align-items-center">
					<div class="col">
						<div class="">
							<h4 class="card-title float-left mt-2" style="font-size: 24px">Tất cả loại phòng</h4>
							<a href="/Admin/AdminRoomType/AddRoomType" class="btn btn-primary float-right veiwbutton" id="menu-create">Thêm loại phòng</a>
						</div>
					</div>
				</div>
				<div class="custom-bulkhead">
					<form style="position: relative">
						<input id="search-input" type="text" class="form-control" placeholder="Tìm kiếm theo tên phòng" name="searchString">
						<p id="submit-button" class="btn" style="position: absolute; top: 0; right: 0"><i class="fas fa-search"></i></p>
					</form>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="card card-table">
						<div class="card-body booking_card">
							<div class="table-responsive">
								<table class="datatable table table-stripped table table-hover table-center mb-0">
									<thead>
										<tr>
											<th style="width: 1%" class="custom-text-center">Mã</th>
											<th style="width: 20%">Tên Loại Phòng</th>
											<th style="width: 10%" class="custom-text-center">Giá</th>
											<th style="width: 10%" class="custom-text-center">Số giường</th>
											<th style="width: 20%" class="custom-text-center">Hình ảnh</th>
											<th style="width: 39%">Chức năng</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in RoomType)
										{

											<tr>
												<td>@item.RoomTypeId</td>
												<td>@item.Name</td>
												<td>@item.Price</td>
												<td>@item.NumBed</td>
												<td><img class="img-100w-50h" src="~/img/avatar-1.jpg" /></td>
												@*<td>
											<img src="/images/@item.Image" style="width: 100%">
											</td>*@
												<td>
													<a data-menu-id="@item.RoomTypeId" class="btn btn-primary btn-sm menu-details">
														<i class="fas fa-pencil-alt"></i>
														Chi tiết
													</a>

													<a data-menu-id="@item.RoomTypeId" class="btn btn-info btn-sm menu-edit">
														<i class="fas fa-pencil-alt"></i>
														Chỉnh sửa
													</a>
													<a data-menu-id="@item.RoomTypeId" class="btn btn-danger btn-sm menu-delete">
														<i class="fas fa-pencil-alt"></i>
														Xóa
													</a>
												</td>
											</tr>
										}

									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel col-4 pl-0 pr-0">
	</div>
</div>