MTKPM-QuanLyKhachSan/Controllers/PublicCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MTKPM_QuanLyKhachSan.Daos;
using MTKPM_QuanLyKhachSan.Models;
using MTKPM_QuanLyKhachSan.ViewModels;

namespace MTKPM_QuanLyKhachSan.Controllers
{
    public class PublicCustomerController : Controller
    {
        CustomerDao customerDao;

        public PublicCustomerController()
        {
            customerDao = new CustomerDao();
        }

        //Đăng nhập
        [HttpGet]
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("Email") == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "PublicHome");
            }
        }
        [HttpPost]
        public IActionResult Login(CustomerVM customerVM)
        {
            ModelState.Remove("Name");
            ModelState.Remove("CustomerId");
            ModelState.Remove("CIC");
            ModelState.Remove("Phone");
            ModelState.Remove("Email");
            ModelState.Remove("Address");
            ModelState.Remove("VerifyPassword");

            if (ModelState.IsValid)
            {
                Customer customer = customerDao.GetCustomerByUserName(customerVM.Username);

                if (customer != null && customer.Password.Equals(customerVM.Password))
                {
                    HttpContext.Session.SetString("Username", customer.Username);
                    HttpContext.Session.SetString("Name", customer.Name);
                    HttpContext.Session.SetInt32("CustomerId", customer.CustomerId);
                    return RedirectToAction("Index", "PublicHome");
                }

                ViewBag.messageError = "Tên đăng nhập hoặc mật khẩu không chính xác!";
            }
            return View();
        }
        //Đăng ký
        [HttpGet]

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(CustomerVM customerVM)
        {
            ModelState.Remove("CustomerId");
            ModelState.Remove("CIC");
            ModelState.Remove("Phone");
            ModelState.Remove("Email");
            ModelState.Remove("Address");
            if (ModelState.IsValid)
            {
                Customer customerRegister = customerDao.GetCustomerByUserName(customerVM.Username);
                if (customerRegister == null)
                {
                    if (customerVM.Password.Equals(customerVM.VerifyPassword))
                    {
                        Customer customer = new Customer()
                        {
                            Username = customerVM.Username,
                            CIC = customerVM.CIC,
                            Phone = customerVM.Phone,
                            Email = customerVM.Email,
                            Address = customerVM.Address,
                            Name = customerVM.Name,
                            Password = customerVM.Password
                        };

                        customerDao.CreateCustomer(customer);

                        return RedirectToAction("Login");
                    }
                    else
                    {
                        ViewBag.messageError = "Mật khẩu xác nhận không khớp";
                    }
                }
                else
                {
                    ViewBag.messageError = "Tài khoản đã tồn tại";
                }
            }
            return View();
        }

        public IActionResult Logout()
        {
            return View();
        }

        public IActionResult Information()
        {
            return View();
        }

        public IActionResult HistoryBooking()
        {
            return View();
        }

        public IActionResult ChangePassword()
        {
            return View();
        }
    }
}

MTKPM-QuanLyKhachSan/Views/PublicCustomer/ChangePassword.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Views/Shared/_CustomerLayout.cshtml";
	var Information = ViewBag.Information;

}
@model CustomerVM
<section class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1>Đổi Mật Khẩu</h1>
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<form method="post" asp-controller="PublicCustomer" asp-action="ChangePassword" class="content" enctype="multipart/form-data">
	<div class="row">
		<div class="col-md-12">
			<div class="card card-primary">

				<div class="card-body">
					<div class="form-group">
						<input type="password" class="form-control" placeholder="Mật khẩu mới" asp-for="Password" required/>
						<span asp-validation-for="@Model.Username" class="text-danger"></span>
						<span class="text-danger">@ViewBag.messageError</span>
					</div>
					<div class="form-group">
						<input type="password" class="form-control" placeholder="Xác nhận mật khẩu" asp-for="VerifyPassword"  />
						<span asp-validation-for="@Model.Username" class="text-danger"></span>
						<span class="text-danger">@ViewBag.messageError</span>
					</div>
					<div class="form-group">
						
						<input type="text" id="inputName" class="form-control" asp-for="Username" value="@Model.Username" hidden>
					</div>
					<div class="form-group">
						
						<input type="text" id="inputName" class="form-control" asp-for="Name" value="@Model.Name" hidden>
					</div>
					<div class="form-group">
						
						<input type="text" id="inputName" class="form-control" asp-for="CIC" value="@Model.CIC" hidden>
					</div>
					<div class="form-group">
						
						<input type="text" id="inputName" class="form-control" asp-for="Phone" value="@Model.Phone" hidden>
					</div>
					<div class="form-group">
						
						<input type="text" id="inputName" class="form-control" asp-for="Email" value="@Model.Email" hidden>
					</div>
					<div class="form-group">
						
						<input type="text" id="inputClientCompany" class="form-control" asp-for="Address" value="@Model.Address" hidden>
					</div>
				</div>
				<!-- /.card-body -->
			</div>
			<!-- /.card -->
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<a asp-controller="PublicCustomer" asp-action="Information" class="btn btn-secondary">Quay về</a>
			<input type="submit" value="Xác nhận" class="btn btn-success float-right">
		</div>
	</div>
</form>
<!-- /.content -->

MTKPM-QuanLyKhachSan/Views/PublicCustomer/EditInformation.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Views/Shared/_CustomerLayout.cshtml";
	var Information = ViewBag.Information;

}
@model CustomerVM
<section class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1>Chỉnh Sửa thông Tin Cá Nhân</h1>
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<form method="post" asp-controller="PublicCustomer" asp-action="EditInformation" class="content" enctype="multipart/form-data">
	<div class="row">
		<div class="col-md-12">
			<div class="card card-primary">
				
				<div class="card-body">

					<div class="form-group">			
						<input type="text" id="inputName" class="form-control" asp-for="Username" value="@Model.Username" hidden>	
					</div>
					<div class="form-group">		
						<input type="text" id="inputName" class="form-control" asp-for="Password" value="@Model.Password" hidden>
					</div>
					<div class="form-group">
						<label for="inputName">Họ Tên</label>
						<input type="text" id="inputName" class="form-control" asp-for="Name" value="@Model.Name">
						<span asp-validation-for="@Model.Name" class="text-danger"></span>
						<span class="text-danger">@ViewBag.messageError</span>
					</div>
					<div class="form-group">
						<label for="inputName">CCCD</label>
						<input type="text" id="inputName" class="form-control" asp-for="CIC" value="@Model.CIC">
						<span asp-validation-for="@Model.CIC" class="text-danger"></span>
						<span class="text-danger">@ViewBag.messageError</span>
					</div>
					<div class="form-group">
						<label for="inputName">SDT</label>
						<input type="text" id="inputName" class="form-control" asp-for="Phone" value="@Model.Phone">
						<span asp-validation-for="@Model.Phone" class="text-danger"></span>
						<span class="text-danger">@ViewBag.messageError</span>
					</div>
					<div class="form-group">
						<label for="inputName">Email</label>
						<input type="text" id="inputName" class="form-control" asp-for="Email" value="@Model.Email">
						<span asp-validation-for="@Model.Email" class="text-danger"></span>
						<span class="text-danger">@ViewBag.messageError</span>
					</div>
					<div class="form-group">
						<label for="inputClientCompany">Địa Chỉ</label>
						<input type="text" id="inputClientCompany" class="form-control" asp-for="Address" value="@Model.Address">
						<span asp-validation-for="@Model.Address" class="text-danger"></span>
						<span class="text-danger">@ViewBag.messageError</span>
					</div>
				</div>
				<!-- /.card-body -->
			</div>
			<!-- /.card -->
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<a asp-controller="PublicCustomer" asp-action="Information" class="btn btn-secondary">Quay về</a>
			<input type="submit" value="Lưu thông tin" class="btn btn-success float-right">
		</div>
	</div>
</form>
<!-- /.content -->

MTKPM-QuanLyKhachSan/Views/PublicCustomer/HistoryBooking.cshtml
@model MTKPM_QuanLyKhachSan.ViewModels.BookingHistory

@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    var BookingList = Model.BookingList;
}

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center mb-5">
                <h2 class="heading-section">Lịch sử đặt phòng</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12">
                @if (BookingList.Any())
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID Đặt phòng</th>
                                <th>ID Khách hàng</th>
                                <th>ID Nhân viên</th>
                                <th>Số lượng Người lớn</th>
                                <th>Số lượng Trẻ nhỏ</th>
                                <th>Ghi chú</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var booking in BookingList)
                            {
                                <tr>
                                    <td>@booking.BookRoomId</td>
                                    <td>@booking.CustomerId</td>
                                    <td>@booking.EmployeeId</td>
                                    <td>@booking.NumAdult</td>
                                    <td>@booking.NumChildren</td>
                                    <td>@booking.Note</td>
                                    
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p>Không tìm thấy lịch sử đặt phòng.</p>
                }
            </div>
        </div>
    </div>
</section>

<!-- Include các file script JS cần thiết -->
<script src="~/customer/Information/js/jquery.min.js"></script>
<script src="~/customer/Information/js/popper.js"></script>
<script src="~/customer/Information/js/bootstrap.min.js"></script>
<script src="~/customer/Information/js/jquery.validate.min.js"></script>
<script src="~/customer/Information/js/main.js"></script>

MTKPM-QuanLyKhachSan/Views/PublicCustomer/Information.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Views/Shared/_CustomerLayout.cshtml";
	var Information = ViewBag.Information;

}
@model CustomerVM
<!doctype html>
<html lang="en">
<head>
	<title>Thông Tin Cá Nhân</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="~/customer/Information/css/style.css">

</head>
<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Thông tin cá Nhân</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-lg-10">
					<div class="wrapper">
						<div class="row no-gutters">
							<div class="col-md-6 d-flex align-items-stretch">
								<div class="contact-wrap w-100 p-md-5 p-4 py-5">
									<h3 class="mb-4">Thông Tin Cá Nhân</h3>
									<div id="form-message-warning" class="mb-4"></div>
									<div id="form-message-success" class="mb-4">
										Your message was sent, thank you!
									</div>
									<form method="POST" id="contactForm" name="contactForm" class="contactForm">
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<p><span>Họ Tên:</span>@Information.Name</p>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<p><span>Email:</span>@Information.Email</p>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<p><span>Tên Đăng Nhập:</span>@Information.Username</p>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<p><span>Password:</span>@Information.Password</p>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<a asp-controller="PublicCustomer" asp-action="ChangePassword" class="btn btn-primary">Đổi Mật Khẩu</a>
													<div class="submitting"></div>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<a asp-controller="PublicCustomer" asp-action="EditInformation" class="btn btn-primary">Chỉnh Sửa Thông Tin Tài Khoản</a>
													<div class="submitting"></div>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="col-md-6 d-flex align-items-stretch">
								<div class="info-wrap w-100 p-md-5 p-4 py-5 img">
									<h3>Contact information</h3>
									<p class="mb-4">We're open for any suggestion or just to have a chat</p>
									<div class="dbox w-100 d-flex align-items-start">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-map-marker"></span>
										</div>
										<div class="text pl-3">
											<p><span>Address:</span>@Information.Address</p>
										</div>
									</div>
									<div class="dbox w-100 d-flex align-items-center">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-phone"></span>
										</div>
										<div class="text pl-3">
											<p><span>Phone:</span> <a href="tel://1234567920">@Information.Phone</a></p>
										</div>
									</div>
									<div class="dbox w-100 d-flex align-items-center">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-paper-plane"></span>
										</div>
										<div class="text pl-3">
											<p><span>CCCD:</span> <a href="mailto:info@yoursite.com">@Information.CIC</a></p>
										</div>
									</div>
									<div class="dbox w-100 d-flex align-items-center">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-globe"></span>
										</div>
										<div class="text pl-3">
											<p><span>Website</span> <a href="#">HotelDelLuna.com</a></p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="~/customer/Information/js/jquery.min.js"></script>
	<script src="~/customer/Information/js/popper.js"></script>
	<script src="~/customer/Information/js/bootstrap.min.js"></script>
	<script src="~/customer/Information/js/jquery.validate.min.js"></script>
	<script src="~/customer/Information/js/main.js"></script>

</body>
</html>


MTKPM-QuanLyKhachSan/Views/PublicCustomer/Login.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
    Layout = null;
}
@model CustomerVM
<!doctype html>
<html lang="en">
<head>
    <title>Hotel Del Luna</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/customer/login/css/style.css">

</head>
<body class="img js-fullheight" style="background-image: url(../../customer/login/images/bg.jpg);">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Hotel Del Luna</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center">Have an account?</h3>
                        <form action="#" method="post" class="signin-form">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Tên Đăng Nhập" asp-for="Username"/>
                                <span asp-validation-for="@Model.Username" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Mật Khẩu" asp-for="Password">
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                                <span class="text-danger">@ViewBag.messageError</span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Đăng nhập" class="form-control btn btn-primary submit px-3"></>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        Lưu mật khẩu
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a asp-controller="PublicCustomer" asp-action="Register" style="color: #fff">Đăng Ký</a>
                                </div>
                            </div>
                        </form>
                        <p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
                        <div class="social d-flex text-center">
                            <a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
                            <a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/customer/login/js/jquery.min.js"></script>
    <script src="~/customer/login/js/popper.js"></script>
    <script src="~/customer/login/js/bootstrap.min.js"></script>
    <script src="~/customer/login/js/main.js"></script>

</body>
</html>

MTKPM-QuanLyKhachSan/Views/PublicCustomer/Register.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
    Layout = null;
}
@model CustomerVM
<!doctype html>
<html lang="en">
<head>
    <title>Hotel Del Luna</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/customer/login/css/style.css">

</head>
<body class="img js-fullheight" style="background-image: url(../../customer/login/images/bg.jpg);">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Hotel Del Luna</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <form action="#" method="post" class="signin-form">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Tên Đăng Nhập" asp-for="Username" />
                                <span asp-validation-for="@Model.Username" class="text-danger"></span>
                                <span class="text-danger">@ViewBag.messageError</span>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Tên người dùng" asp-for="Name">
                                <span asp-validation-for="@Model.Name" class="text-danger"></span>
                                <span class="text-danger">@ViewBag.messageError</span>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Mật Khẩu" asp-for="Password">
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                                <span class="text-danger">@ViewBag.messageError</span>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Xác nhận mật khẩu" asp-for="VerifyPassword">
                                <span asp-validation-for="@Model.VerifyPassword" class="text-danger"></span>
                                <span class="text-danger">@ViewBag.messageError</span>
                            </div>               
                            <div class="form-group">
                                <input type="submit" value="Đăng Ký" class="form-control btn btn-primary submit px-3"></>
                            </div> 
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/customer/login/js/jquery.min.js"></script>
    <script src="~/customer/login/js/popper.js"></script>
    <script src="~/customer/login/js/bootstrap.min.js"></script>
    <script src="~/customer/login/js/main.js"></script>

</body>
</html>