MTKPM-QuanLyKhachSan/Areas/Admin/Controllers/AdminRoomController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using MTKPM_QuanLyKhachSan.Daos;
using MTKPM_QuanLyKhachSan.Models;
using MTKPM_QuanLyKhachSan.ViewModels;
using System.Diagnostics;
using System.Drawing.Drawing2D;
using System;
using MTKPM_QuanLyKhachSan.Areas.Admin.DesignPattern.Strategy;
using Humanizer.Localisation.TimeToClockNotation;
using MTKPM_QuanLyKhachSan.Areas.Admin.DesignPattern.Singleton;
using MTKPM_QuanLyKhachSan.Common.Config;

namespace MTKPM_QuanLyKhachSan.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("Admin/[controller]/[action]")]
	public class AdminRoomController : Controller
	{
		RoomDao roomDao;
		private StrategyDatabase roomStrategy;
		private readonly Under5HundredRoom _under5HundredRoom;
		private readonly DoubleRooms _doubleRoom;
		private readonly StandardRooms _standardRooms;
		IService myService;

		public AdminRoomController(DatabaseContext context, IService myService, Under5HundredRoom under5HundredRoom, DoubleRooms doubleRoom, StandardRooms standardRooms)
		{
			this.myService = myService;
			roomDao = new RoomDao(context);
			_under5HundredRoom = under5HundredRoom;
			_doubleRoom = doubleRoom;
			_standardRooms = standardRooms;
		}
		public IActionResult Index()
		{
			ViewBag.Room = roomDao.GetRooms(myService.GetHotelId());
			return View();
		}

		public void SetRoomStrategy(StrategyDatabase strategy)
		{
			roomStrategy = strategy;
		}
		public IActionResult LuxuryRooms(int roomId)
		{
			var rooms = _under5HundredRoom.RoomStrategy(roomId);
			ViewBag.Room = rooms;
			return View();
		}
		public IActionResult DoubleRooms(int roomId)
		{
			var rooms = _doubleRoom.RoomStrategy(roomId);
			ViewBag.Room = rooms;
			return View();
		}

		public IActionResult StandardRooms(int roomId)
		{
			var rooms = _standardRooms.RoomStrategy(roomId);
			ViewBag.Room = rooms;
			return View();
		}

		[HttpGet]
		public IActionResult AddRoom()
		{
			return View();
		}
		[HttpPost]
		public IActionResult AddRoom(RoomVM roomVM)
		{
			ModelState.Remove("RoomId");
			Room room = new Room()
			{
				RoomId = roomVM.RoomId,
				Name = roomVM.Name,
				Status = roomVM.Status,
				RoomTypeId = roomVM.RoomTypeId,
				Tidy = roomVM.Tidy,
				HotelId = myService.GetHotelId(),
			};
			SingletonDatabase.Instance.Rooms.Add(room);
			SingletonDatabase.Instance.SaveChanges();
			//roomDao.InsertRoom(room);
			return RedirectToAction("Index");
		}
		[HttpPost]
		public IActionResult DeleteRoom(int roomId)
		{
			SingletonDatabase.Instance.Rooms.Remove(SingletonDatabase.Instance.Rooms.FirstOrDefault(i => i.RoomId == roomId));
			SingletonDatabase.Instance.SaveChanges();
			ExecutionOutcome executionOutcome = new ExecutionOutcome()
			{
				Result = true,
				Mess = "Xóa phòng thành công."
			};

			return Json(executionOutcome);
		}
		[HttpGet]
		public IActionResult DetailsRoom(int roomId)
		{
			Room room = SingletonDatabase.Instance.Rooms.FirstOrDefault(i => i.RoomId == roomId);
			RoomVM roomVM = new RoomVM()
			{
				RoomId = room.RoomId,
				Name = room.Name,
				Status = room.Status,
				RoomTypeId = room.RoomTypeId,
				Tidy = room.Tidy,
			};
			return PartialView(roomVM);

		}
		[HttpPost]
		public IActionResult DeltailsRoom(RoomVM roomVM)
		{
			SingletonDatabase.Instance.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult EditRoom(int roomId)
		{
			Room room = SingletonDatabase.Instance.Rooms.FirstOrDefault(i => i.RoomId == roomId);
			RoomVM roomVM = new RoomVM()
			{
				RoomId = room.RoomId,
				Name = room.Name,
				Status = room.Status,
				RoomTypeId = room.RoomTypeId,
				Tidy = room.Tidy,
			};
			return PartialView(roomVM);
		}
		[HttpPost]
		public IActionResult EditRoom(RoomVM roomVM)
		{
			Room room = new Room()
			{
				RoomId = roomVM.RoomId,
				Name = roomVM.Name,
				Status = roomVM.Status,
				RoomTypeId = roomVM.RoomTypeId,
				Tidy = roomVM.Tidy,
				HotelId = myService.GetHotelId(),
			};

			//roomDao.EditRoom(room);
			ExecutionOutcome executionOutcome = new ExecutionOutcome()
			{
				Result = true,
				Mess = "Cập nhật phòng thành công."
			};

			//SingletonDatabase.Instance.Rooms.Update(room);
			//SingletonDatabase.Instance.SaveChanges();
			roomDao.EditRoom(room);
			return Ok(executionOutcome);
		}
	}
}

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoom/AddRoom.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using MTKPM_QuanLyKhachSan.ViewModels
@model RoomVM



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="colorlib.com">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="~/admin/assets/adminRoomtype/fonts/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/admin/assets/adminRoomtype/vendor/nouislider/nouislider.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="~/admin/assets/adminRoomtype/css/style.css">
</head>

<body>

    <div class="main">

        <div class="container">
            <form method="POST" id="signup-form" class="signup-form" asp-controller="AdminRoom" asp-action="AddRoom" asp-area="Admin">
                <div>
                    <h3>Phòng </h3>
                    <fieldset>
                        <h2>Thêm Loại Phòng</h2>
                        <div class="fieldset-content">
                            <div class="form-row">
                                <div class="form-flex">
                                    <div class="form-group">
                                        <label class="form-label">Tên</label>
                                        <input type="number" id="first_name" asp-for="Name" />
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Loại Phòng</label>
                                        <input type="number" id="last_name" asp-for="RoomTypeId" />
                                    </div>
                                </div>
                            </div>       
                            <div class="form-group">
                                @*<label  for="ssn" class="form-label">Hình ảnh</label>
                                <input width: 300px type="text" name="ssn" id="ssn" />*@
                            </div>
                            <div class="form-group">
                                <label class="form-label">Trạng Thái phòng</label>
                                <input type="number" id="last_name" asp-for="Status" />
                            </div>
                            <div class="form-group">
                                <label class="form-label">Dọn Dẹp</label>
                                <input type="number" id="last_name" asp-for="Tidy " />
                            </div>
                        </div>
                        <div class="">
                            <input id="submit-input" type="submit" value="Lưu">
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>

    <!-- JS -->
    <script src="~/admin/assets/adminRoomtype/vendor/jquery/jquery.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/jquery-steps/jquery.steps.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/minimalist-picker/dobpicker.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/nouislider/nouislider.min.js"></script>
    <script src="~/admin/assets/adminRoomtype/vendor/wnumb/wNumb.js"></script>
    <script src="~/admin/assets/adminRoomtype/js/main.js"></script>*
</body>

</html>

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoom/DetailsRoom.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = null;
}
@model RoomVM

<form id="form-details-account">
	<!-- Lưu đặt phòng -->
	<div class="panel-save d-flex justify-content-between align-items-center">
		<span>Chi tiết </span>
	</div>

	<!-- Form -->
	<div class="panel-form">
		<!-- Thông tin -->
		<div class="panel-form-info">
			<!-- Tên tài khoản -->
			<div class="panel-form-item">
				<h5 class="panel-form-title">Mã</h5>
				<input class="panel-form-input" type="text" name="Name" value="@Model.RoomId" readonly />
			</div>

			<!-- Tên tài khoản -->
			<a class="panel-form-item">
				<h5 class="panel-form-title">Tên Phòng</h5>
				<input class="panel-form-input" type="text" name="Username" value="@Model.Name" readonly />
			</a>

			<a class="panel-form-item">
				<h5 class="panel-form-title">Trạng thái</h5>
				<input class="panel-form-input" type="text" name="Username" value="@Model.Status" readonly />
			</a>

			<a class="panel-form-item">
				<h5 class="panel-form-title">Loại Phòng</h5>
				<input class="panel-form-input" type="text" name="Username" value="@Model.RoomTypeId" readonly />
			</a>

			<a class="panel-form-item">
				<h5 class="panel-form-title">Dọn dẹp</h5>
				<input class="panel-form-input" type="text" name="Username" value="@Model.Tidy" readonly />
			</a>

			<!-- Mật khẩu -->
			

				@*<!-- Tên tài khoản -->
				<div class="panel-form-item">
				<h5 class="panel-form-title">Giới tính</h5>
				<input class="panel-form-input" type="text" />
				</div>

				<!-- Tên tài khoản -->
				<div class="panel-form-item">
				<h5 class="panel-form-title">Ngày sinh</h5>
				<input class="panel-form-input" type="text" />
				</div>

				<!-- Tên tài khoản -->
				<div class="panel-form-item">
				<h5 class="panel-form-title">Số điện thoại</h5>
				<input class="panel-form-input" type="text" />
				</div>

				<!-- Tên tài khoản -->
				<div class="panel-form-item">
				<h5 class="panel-form-title">Địa chỉ</h5>
				<input class="panel-form-input" type="text" />
				</div>

				<!-- Tên tài khoản -->
				<div class="panel-form-item">
				<h5 class="panel-form-title">Email</h5>
				<input class="panel-form-input" type="text" />
				</div>*@
			</div>
		</div>
	</div>
</form>

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoom/DoubleRooms.cshtml
﻿﻿@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	var Room = ViewBag.Room;
}
@model RoomVM

<div class="main-container d-flex">
	<!-- Nội dung bên trái -->
	<div class="left-panel col-8 pl-0 pr-0">
		<div class="content container-fluid">
			<div class="page-header">
				<div class="row align-items-center">
					<div class="col">
						<div class="">
							<h4 class="card-title float-left mt-2" style="font-size: 24px">Phòng</h4>
							<a href="/Admin/AdminRoom/AddRoom" class="btn btn-primary float-right veiwbutton" id="menu-create">Thêm phòng</a>
						</div>
					</div>
				</div>
				<div class="custom-bulkhead">
					<!-- Thanh mục lục -->
					<ul class="nav">
						<li class="nav-item">
							<a href="/Admin/AdminRoom/LuxuryRooms" class="nav-link">Phòng cao cấp</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/DoubleRooms" class="nav-link">Phòng đôi</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/StandardRooms" class="nav-link">Phòng thường</a>
						</li>
					</ul>
				</div>

			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="card card-table">
						<div class="card-body booking_card">
							<div class="table-responsive">
								<table class="datatable table table-stripped table table-hover table-center mb-0">
									<thead>
										<tr>
											<th style="width: 1%" class="custom-text-center">Mã</th>
											<th style="width: 20%">Tên</th>
											<th style="width: 10%" class="custom-text-center">Trạng thái</th>
											<th style="width: 15%" class="custom-text-center">Loại phòng</th>
											<th style="width: 15%" class="custom-text-center">Dọn dẹp</th>
											<th style="width: 39%">Chức năng</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Room)
										{

											<tr>
												<td>@item.RoomId</td>
												<td>@item.Name</td>
												<td>@item.Status</td>
												<td>@item.RoomTypeId</td>
												<td>@item.Tidy</td>
												@*<td>
											<img src="/images/@item.Image" style="width: 100%">
											</td>*@
												<td>
													<a data-room-id="@item.RoomId" class="edit-room btn btn-primary btn-sm ">
														<i class="fas fa-pencil-alt"></i>
														Chỉnh sửa
													</a>
													<a data-room-id="@item.RoomId" class="details-room btn btn-info btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Chi tiết
													</a>
													<a data-room-id="@item.RoomId" onclick="deleteRoom(@item.RoomId)" class="delete-room btn btn-danger btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Xóa
													</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel col-4 pl-0 pr-0">
	</div>
</div>

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoom/EditRoom.cshtml
@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = null;
}
@model RoomVM

<form id="form-edit-room" >
	<!-- Lưu đặt phòng -->
	<div class="panel-save d-flex justify-content-between align-items-center">
		<span>Cập nhật </span>

		<div class="">
			<input type="submit" value="Lưu" />
		</div>
	</div>

	<!-- Form -->
	<div class="panel-form">
		<!-- Thông tin -->
		<div class="panel-form-info">
			<!-- Tên tài khoản -->
			<div class="panel-form-item">
				<h5 class="panel-form-title">Mã</h5>
				<input class="panel-form-input" type="text" name="RoomId" value="@Model.RoomId" readonly  />
			</div>

			<!-- Tên tài khoản -->
			<a class="panel-form-item">
				<h5 class="panel-form-title">Tên Phòng</h5>
				<input class="panel-form-input" type="number" name="Name" value="@Model.Name" />
			</a>

			<a class="panel-form-item">
				<h5 class="panel-form-title">Trạng thái</h5>
				<input class="panel-form-input" type="number" name="Status" value="@Model.Status" />
			</a>

			<a class="panel-form-item">
				<h5 class="panel-form-title">Loại Phòng</h5>
				<input class="panel-form-input" type="numebr" name="RoomTypeId" value="@Model.RoomTypeId" />
			</a>

			<a class="panel-form-item">
				<h5 class="panel-form-title">Dọn dẹp</h5>
				<input class="panel-form-input" type="number" name="Tidy" value="@Model.Tidy" />
			</a>		
		</div>
	</div>
</form>

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoom/Index.cshtml
﻿﻿@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	var Room = ViewBag.Room;
}
@model RoomVM

<div class="main-container d-flex">
	<!-- Nội dung bên trái -->
	<div class="left-panel col-8 pl-0 pr-0">
		<div class="content container-fluid">
			<div class="page-header">
				<div class="row align-items-center">
					<div class="col">
						<div class="">
							<h4 class="card-title float-left mt-2" style="font-size: 24px">Phòng</h4>
							<a href="/Admin/AdminRoom/AddRoom" class="btn btn-primary float-right veiwbutton" id="menu-create">Thêm phòng</a>
						</div>
					</div>
				</div>
				<div class="custom-bulkhead">
					<!-- Thanh mục lục -->
					<ul class="nav">
						<li class="nav-item">
							<a href="/Admin/AdminRoom/LuxuryRooms" class="nav-link">Phòng cao cấp</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/DoubleRooms" class="nav-link">Phòng đôi</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/StandardRooms" class="nav-link">Phòng thường</a>
						</li>
					</ul>
				</div>

			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="card card-table">
						<div class="card-body booking_card">
							<div class="table-responsive">
								<table class="datatable table table-stripped table table-hover table-center mb-0">
									<thead>
										<tr>
											<th style="width: 1%" class="custom-text-center">Mã</th>
											<th style="width: 20%">Tên</th>
											<th style="width: 10%" class="custom-text-center">Trạng thái</th>
											<th style="width: 15%" class="custom-text-center">Loại phòng</th>
											<th style="width: 15%" class="custom-text-center">Dọn dẹp</th>
											<th style="width: 39%">Chức năng</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Room)
										{

											<tr>
												<td>@item.RoomId</td>
												<td>@item.Name</td>
												<td>@item.Status</td>
												<td>@item.RoomTypeId</td>
												<td>@item.Tidy</td>
												@*<td>
											<img src="/images/@item.Image" style="width: 100%">
											</td>*@
												<td>
													<a data-room-id="@item.RoomId" class="edit-room btn btn-primary btn-sm ">
														<i class="fas fa-pencil-alt"></i>
														Chỉnh sửa 
													</a>
													<a data-room-id="@item.RoomId" class="details-room btn btn-info btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Chi tiết
													</a>
													<a data-room-id="@item.RoomId" onclick="deleteRoom(@item.RoomId)" class="delete-room btn btn-danger btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Xóa
													</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel col-4 pl-0 pr-0">
	</div>
</div>

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoom/LuxuryRooms.cshtml
﻿﻿@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	var Room = ViewBag.Room;
}
@model RoomVM

<div class="main-container d-flex">
	<!-- Nội dung bên trái -->
	<div class="left-panel col-8 pl-0 pr-0">
		<div class="content container-fluid">
			<div class="page-header">
				<div class="row align-items-center">
					<div class="col">
						<div class="">
							<h4 class="card-title float-left mt-2" style="font-size: 24px">Phòng</h4>
							<a href="/Admin/AdminRoom/AddRoom" class="btn btn-primary float-right veiwbutton" id="menu-create">Thêm phòng</a>
						</div>
					</div>
				</div>
				<div class="custom-bulkhead">
					<!-- Thanh mục lục -->
					<ul class="nav">
						<li class="nav-item">
							<a href="/Admin/AdminRoom/LuxuryRooms" class="nav-link">Phòng cao cấp</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/DoubleRooms" class="nav-link">Phòng đôi</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/StandardRooms" class="nav-link">Phòng thường</a>
						</li>
					</ul>
				</div>

			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="card card-table">
						<div class="card-body booking_card">
							<div class="table-responsive">
								<table class="datatable table table-stripped table table-hover table-center mb-0">
									<thead>
										<tr>
											<th style="width: 1%" class="custom-text-center">Mã</th>
											<th style="width: 20%">Tên</th>
											<th style="width: 10%" class="custom-text-center">Trạng thái</th>
											<th style="width: 15%" class="custom-text-center">Loại phòng</th>
											<th style="width: 15%" class="custom-text-center">Dọn dẹp</th>
											<th style="width: 39%">Chức năng</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Room)
										{

											<tr>
												<td>@item.RoomId</td>
												<td>@item.Name</td>
												<td>@item.Status</td>
												<td>@item.RoomTypeId</td>
												<td>@item.Tidy</td>
												@*<td>
											<img src="/images/@item.Image" style="width: 100%">
											</td>*@
												<td>
													<a data-room-id="@item.RoomId" class="edit-room btn btn-primary btn-sm ">
														<i class="fas fa-pencil-alt"></i>
														Chỉnh sửa
													</a>
													<a data-room-id="@item.RoomId" class="details-room btn btn-info btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Chi tiết
													</a>
													<a data-room-id="@item.RoomId" onclick="deleteRoom(@item.RoomId)" class="delete-room btn btn-danger btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Xóa
													</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel col-4 pl-0 pr-0">
	</div>
</div>

MTKPM-QuanLyKhachSan/Areas/Admin/Views/AdminRoom/StandardRooms.cshtml
﻿﻿@using MTKPM_QuanLyKhachSan.ViewModels
@{
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	var Room = ViewBag.Room;
}
@model RoomVM

<div class="main-container d-flex">
	<!-- Nội dung bên trái -->
	<div class="left-panel col-8 pl-0 pr-0">
		<div class="content container-fluid">
			<div class="page-header">
				<div class="row align-items-center">
					<div class="col">
						<div class="">
							<h4 class="card-title float-left mt-2" style="font-size: 24px">Phòng</h4>
							<a href="/Admin/AdminRoom/AddRoom" class="btn btn-primary float-right veiwbutton" id="menu-create">Thêm phòng</a>
						</div>
					</div>
				</div>
				<div class="custom-bulkhead">
					<!-- Thanh mục lục -->
					<ul class="nav">
						<li class="nav-item">
							<a href="/Admin/AdminRoom/LuxuryRooms" class="nav-link">Phòng cao cấp</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/DoubleRooms" class="nav-link">Phòng đôi</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/AdminRoom/StandardRooms" class="nav-link">Phòng thường</a>
						</li>
					</ul>
				</div>

			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="card card-table">
						<div class="card-body booking_card">
							<div class="table-responsive">
								<table class="datatable table table-stripped table table-hover table-center mb-0">
									<thead>
										<tr>
											<th style="width: 1%" class="custom-text-center">Mã</th>
											<th style="width: 20%">Tên</th>
											<th style="width: 10%" class="custom-text-center">Trạng thái</th>
											<th style="width: 15%" class="custom-text-center">Loại phòng</th>
											<th style="width: 15%" class="custom-text-center">Dọn dẹp</th>
											<th style="width: 39%">Chức năng</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Room)
										{

											<tr>
												<td>@item.RoomId</td>
												<td>@item.Name</td>
												<td>@item.Status</td>
												<td>@item.RoomTypeId</td>
												<td>@item.Tidy</td>
												@*<td>
											<img src="/images/@item.Image" style="width: 100%">
											</td>*@
												<td>
													<a data-room-id="@item.RoomId" class="edit-room btn btn-primary btn-sm ">
														<i class="fas fa-pencil-alt"></i>
														Chỉnh sửa
													</a>
													<a data-room-id="@item.RoomId" class="details-room btn btn-info btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Chi tiết
													</a>
													<a data-room-id="@item.RoomId" onclick="deleteRoom(@item.RoomId)" class="delete-room btn btn-danger btn-sm">
														<i class="fas fa-pencil-alt"></i>
														Xóa
													</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel col-4 pl-0 pr-0">
	</div>
</div>